name: e
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_settings_screens: ^0.3.4
  share_plus: ^9.0.0
  flutter_spinkit: ^5.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.9
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"  
  image: assets/images/profilepic.jpg
  image_dark: assets/images/profilepic.jpg
  android: true  
  ios: true  
  android_gravity: center
  ios_content_mode: center
  android_background_color: Colors.white
  ios_background_color: Colors.white
