name: iOS Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ios:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./flutter_project
        run: flutter pub get

      - name: Build iOS .app
        working-directory: ./flutter_project
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        working-directory: ./flutter_project
        run: |
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -r App.ipa Payload/
          rm -rf Payload


      - name: Upload Release IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ./flutter_project/App.ipa