name: macOS Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./flutter_project
        run: flutter pub get

      - name: Build macOS .app
        working-directory: ./flutter_project
        run: flutter build macos

      - name: Upload Release app
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: ./flutter_project/build/macos/Build/Products/Release/*.app