name: Windows Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        working-directory: ./flutter_project
        run: flutter pub get

      - name: Build Windows exe
        working-directory: ./flutter_project
        run: flutter build windows

      - name: Upload Release exe
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ./flutter_project/build/windows/x64/runner/Release/*.exe